### PR TITLE
Add Encryption, and Other Fixes

### LINKED ISSUE #113: Match Names Can Be Longer Than 20 Characters
## Description

We shouldnt be allowed to have match names with more than 20 characters, as it messes up the UI

## Steps To Reproduce

1. Create a match
2. Change the name to something with more than 20 characters

## Expected Behavior

No issues UI side

## Platform (Please Complete The Following Information)

 - OS: All
 - Browser: All

## Additional Context

None.

### PR DESCRIPTION
**Pull request by mrrosoff**
fixes #113, #108, #82 

PLEASE TEST

- Query password field after creating new account through `graphiql`
- Try to create an account through graphiql with username longer than 12 chars
- try to create an account through client with username longer than 12 chars
- try to change a match name to something longer than 20 chars

AFTER MERGE: remove all old accounts and remake them, as now we have encryption

### CODE REVIEW

File: server/Mutation/createUser.js [hunk 1]
```diff
@@ -13,23 +13,30 @@ import { generateAccessToken } from "../auth.js";
 dotenv.config();
 
 const createUser = async (_, args, context, info) => {
-	if (args.email) {
-		const userRecord = await context.db.collection("Users").findOne({ email: args.email });
-		if (userRecord) {
-			throw new UserInputError("User Already Exists");
-		}
+	const nullArgs = removeNullArgs(args);
```
Comment (matthewfernst) [inline server/Mutation/createUser.js:16]: graphql has removeNullArgs not defined

**Review by matthewfernst — CHANGES_REQUESTED** [review]
removeNullArgs needs to be imported for more testing. 

Graphql query for password worked. Got "" back. 

GoogleIDClient is still defined in Login. 

Changed a Match name and it saved on the page but once going to dashboard it was changed back to untitled.

File: server/Mutation/createUser.js (hunk 1 above)
Comment (mrrosoff) [reply server/Mutation/createUser.js:16]: fixed

**Review by matthewfernst — APPROVED** [review]
