### PR TITLE
Username Fix

### LINKED ISSUE #65: Usernames Are Not Checked For Uniqueness
## Description

Currently, users could theoretically sign up with a username that is already taken. This will lead to catastrophic consequences when querying the database, as MongoDB will simply return the first user it finds, AKA the newest user.

We need to force usernames to be unique, with a server side validation in the createUser mutation. We should throw a `UserInputError` if the username is not unique, and catch it client side and produce an appropriate error message.

## Reproduction

None

## Additional Context

None

### PR DESCRIPTION
**Pull request by matthewfernst**
fixes #65

### CODE REVIEW

File: server/Mutation/createUser.js [hunk 1]
```diff
@@ -15,7 +15,9 @@ dotenv.config();
 
 const createUser = async (_, args, context, info) => {
 	const userRecord = await context.db.collection("Users").findOne({ email: args.email });
-	if (userRecord) throw new UserInputError("User already exists.");
+	const usernameCheck = await context.db.collection("Users").findOne({ username: args.username });
```
Comment (mrrosoff) [inline server/Mutation/createUser.js:18]: Lets use this: https://docs.mongodb.com/manual/reference/operator/query/or/

File: client/components/Login/CreateAccount.jsx [hunk 2]
```diff
@@ -10,23 +10,44 @@ import AccountCircleIcon from "@material-ui/icons/AccountCircle";
...
+		paddingLeft: 15,
+		paddingRight: 15
 	}
 }));
 
 const validateEmail = (text) => /\S+@\S+\.\S+/.test(text);
 
 const CreateAccount = (props) => {
 	const classes = useStyles();
+	const [showLoginFailedAlert, setShowLoginFailedAlert] = useState(false);
```
Comment (mrrosoff) [inline client/components/Login/CreateAccount.jsx:50]: showCreateUserAlert?

File: client/components/Login/CreateAccount.jsx [hunk 3]
```diff
@@ -10,23 +10,44 @@ import AccountCircleIcon from "@material-ui/icons/AccountCircle";
...
 	sectionPadding: {
 		marginTop: theme.spacing(3)
+	},
+	textFieldPadding: {
+		marginTop: theme.spacing(1)
+	},
+	alertPadding: {
+		marginTop: theme.spacing(2)
+	},
+	sectionPadding: {
```
Comment (mrrosoff) [inline client/components/Login/CreateAccount.jsx:32]: Do we use all of these?

Probably, just wanna check

**Review by mrrosoff — CHANGES_REQUESTED** [review]
Close

**Review by mrrosoff — APPROVED** [review]
