### PR TITLE
Board and Piece Skin Now Selected

### LINKED ISSUE #63: Cannot Change Board or Piece Skin
## Description

Currently, in the pregame lobby, selecting a skin (that is owned by the user), does not properly select the item for the game. This issue happens at both the client and server side, which leads me to believe it is an underlying server issue.

## Steps To Reproduce

1. Create a match
2. Attempt to select an alternative skin from the defaults
3. Notice how although there are no errors, the new skin is not selected

## Additional Context

None

### PR DESCRIPTION
**Pull request by matthewfernst**
fixes #63

### CODE REVIEW

**Review by mrrosoff — CHANGES_REQUESTED** [review]

File: client/components/App/Match/Match.jsx [hunk 1]
```diff
@@ -34,7 +34,26 @@ const Match = (props) => {
 		variables: { _id: matchId }
 	});
 
-	const [editMatch] = useMutation(EditMatch);
+	const [editMatch] = useMutation(EditMatch, {
```
Comment (mrrosoff) [inline client/components/App/Match/Match.jsx:37]: We can't do this merge function. They can edit a ton of things. We get all the data back from editMatch, let's just flat out replace the old version. I think thats the default behavior, so let's remove this function.

File: server/Mutation/editMatch.js [hunk 2]
```diff
@@ -11,13 +12,29 @@ const editMatch = async (_, args, context, info) => {
...
 		throw new UserInputError("Must Be Match Owner For Mutation Request");
 	}
-	const modifiedMatch = await context.db
-		.collection("Matches")
-		.findOneAndUpdate(
+
+	const nullArgs = removeNullArgs(args);
+	let modifiedMatch = null;
+
+	if (nullArgs.boardSkin || nullArgs.pieceSkin) {
```
Comment (mrrosoff) [inline server/Mutation/editMatch.js:19]: This is on the right track, but I think we should do the following. 

if(nullArgs.boardSkin) nullArgs.boardSkin = ObjectId(nullArgs.boardSkin)

Same for piece Skin

Then directly set nullArgs

**Review by mrrosoff — CHANGES_REQUESTED** [review]

**Review by mrrosoff — APPROVED** [review]
